folio-org/folio-org.github.io

community/index.md, doc/index.md, source-code/index.md
This is ready to merge.
Link to the enhanced document at Wiki "FOLIO Communication Spaces".
Add a Guidelines section.
We can later add specific developer notes as needed.
=> FOLIO-293 communication spaces

_config.yml, _includes/footer.html, community/guide-issues.md, community/index.md, community/which-forum.md, doc/glossary.md, doc/index.md, source-code/index.md
Ready to merge. I will do so tomorrow.
Addresses FOLIO-293 with the community/which-forum doc.
Also addresses FOLIO-298 with the community/guide-issues doc.
=> More on which forum and guide issues

.gitignore, Makefile, README.md, _config.yml, community/contrib-code.md, md2toc, target/index.md
Copied the md2toc generator from okapi/doc
Thanks to Mike Taylor
=> Add ToC generator

community/contrib-code.md, community/which-forum.md, doc/index.md
=> FOLIO-320 coding style

source-code/index.md
=> Document the master locations of RAMLs

community/contrib-code.md
=> FOLIO-303 Expand contrib-code to explain fork-and-pull

doc/index.md, doc/setup.md, doc/troubleshooting.md
=> Commence general troubleshooting doc

_data/api.yml, doc/api/index.md
=> New YAML structure to handle multiple RAML sets per repository

_data/api.yml
Removed catalogue and knowledgebase
Renamed inventory
=> DMOD-133: Follow removal of RAML files: mod-metadata (DMOD-133)

doc/index.md, doc/troubleshooting.md, source-code/index.md
Generally tidy the “doc” and “source-code” sections.
Improve links to Stripes docs and running complete system.
=> STRIPES-210 tidy

_data/api.yml, doc/api/index.md
=> DMOD-133 move config user related ramls

doc/setup.md, doc/troubleshooting.md
Troubleshooting: regular user; Postrgres
Setup: PostgreSQL
=> Tweak docs 1

README.md, _config.yml, work/README.md, work/guide-theme.md
Add a “work” area for notes (is not published to dev.f.o).
Add guidelines for theme improvement.
=> FOLIO-643 guide theme

community/index.md, doc/index.md, doc/primer-develop-frontend.md, doc/reference.md
Add “guide” sections as general topics.
=> FOLIO-646 add guides sections

_includes/header.html, _sass/_folio.scss
First top bar links to main other sites.
Second top bar links to dev major sections.
=> FOLIO-646 two top nav bars

source-code/index.md
Add recent repositories to source-code/index.md
=> FOLIO-359 add repo 1

_sass/_folio.scss, doc/api/index.md
Add rowspans to API docs table.
Enable link to all of a module’s table rows.
Add basic table CSS.
=> FOLIO-672 rowspan

doc/create-new-repo.md, doc/index.md
=> FOLIO-722 doc new repo

_data/api.yml, source-code/index.md
=> FOLIO-359 list repos 3

_data/api.yml, source-code/index.md
Add mod-circulation
Add mod-login-saml
=> FOLIO-359 list repos 4

community/guide-issues.md, community/index.md, community/which-forum.md, doc/index.md
Use table for concise list of forums
=> Improve docs 5

doc/glossary.md, doc/index.md
Link new doc : Stripes entities
=> Improve docs 6

doc/index.md, source-code/index.md
Add repo eslint-config-stripes.
Link to SonarQube analysis.
=> Improve docs 7

_includes/column-2-search.html, _sass/_folio.scss, assets/js/search-dev.js, search.md, search_data.json
Initial search facility using bvaughn/js-search
=> FOLIO-860 add js search

doc/any-programming-language.md, doc/glossary.md, doc/index.md, doc/primer-develop-backend.md, doc/setup.md
It is ready to merge and can be enhanced later.
I will wait a while because i would appreciate review.
=> FOLIO-866 doc any programming language

source-code/index.md
Add mod-user-import.
Follow rename stripes-util-notes to stripes-smart-components.
=> FOLIO-359 list repos 5

community/contrib-code.md, doc/code-analysis.md, doc/index.md, doc/setup.md
Explain code analysis and linting facilities.
=> FOLIO-880 doc code analysis

about/thanks.md, community/contrib-code.md
=> FOLIO-873 improve docs 8

community/contrib-code.md, doc/setup.md, source-code/index.md
Emphasise license in contrib-code doc.
Remind no license header.
=> FOLIO-873 improve docs 10

_data/api.yml
Add fixed-due-date-schedule for mod-circulation-storage
=> FOLIO-903-api-docs-config-1

doc/glossary.md, doc/index.md
=> FOLIO-873 improve docs 11

_data/api.yml, assets/js/search-dev.js, source-code/index.md
Add shelf-location for mod-inventory-storage
=> FOLIO-873 improve docs 12

source-code/index.md
=> FOLIO-359 list repos 7

_data/api.yml
Add proxiesFor to raml mod-users
=> FOLIO-903-api-docs-config-2

source-code/index.md
=> FOLIO-359 list repos 8

_data/api.yml
Add instance-format, instance-type, classification-type,
contributor-type, creator-type, identifier-type for
mod-inventory-storage
=> FOLIO-903 api-docs config 3

_data/api.yml
=> FOLIO-903 api-docs config 4

_data/api.yml
=> FOLIO-903 api-docs config 5

_data/api.yml
Add holdings-storage for mod-inventory-storage
=> FOLIO-903 api-docs config 6

source-code/index.md
Add ui-search, mod-codex-mock, mod-codex-mux, folio-tools
=> FOLIO-359 list repos 10

doc/create-new-repo.md, doc/setup.md
Improve doc/create-new-repo.md
Emphasise early steps and adding teams.
=> FOLIO-873 improve docs 14

_includes/column-2-community-guide-issues.html, community/contrib-code.md, community/guide-issues.md, community/which-forum.md
Improve “guide-issues” and the lead-in docs to encourage reports of various issues.
=> FOLIO-959 improve guide issues

_data/api.yml
Add contact_category vendor_category for mod-vendors
=> FOLIO-903 api-docs config 7

_data/api.yml, source-code/index.md
Add mod-finance.
Rename mod-vendors.
=> FOLIO-359 list repos 11

_data/api.yml
Follow move of ramls directory raml-module-builder
=> FOLIO-903 api-docs config 8

community/guide-issues.md, doc/create-new-repo.md, doc/release-procedures.md, source-code/index.md
Link to okapi.rb (okapi-cli).
Fix some links.
Choose repo name wisely.
=> FOLIO-873 improve docs 16

source-code/index.md
=> FOLIO-359 list repos 12

doc/reference.md
Removing the test.
See comments in pull #120
=> FOLIO-964 test permalink 2

_data/api.yml
Added platform for mod-inventory-storage
=> FOLIO-903 api-docs config 9

work/amazon-web-services/website-master_cloudformation.yml
=> Add 's3:delete' permission to CodeBuildServiceRole

work/amazon-web-services/website-master_cloudformation.yml
Temporarily reverting the modification to add s3:delete to the CodeBuild
role in order to test the error handling.
=> Add CodeBuildFailedTopicPolicy and revert s3:delete

work/amazon-web-services/website-master_cloudformation.yml
Fixes FOLIO-991 and puts back the changes that were in FOLIO-990.
=> Fix CodeBuildFailedTopicPolicy

about/index.md, about/thanks.md, community/cla-process.md, community/contrib-code.md, community/guide-issues.md, community/index.md, community/which-forum.md, doc/any-programming-language.md, doc/api/index.md, doc/automation.md, doc/best-practices-dockerfiles.md, doc/code-analysis.md, doc/create-new-repo.md, doc/glossary.md, doc/index.md, doc/primer-develop-backend.md, doc/primer-develop-frontend.md, doc/release-procedures.md, doc/setup.md, doc/troubleshooting.md, index.md, search-other.md, search.md, source-code/index.md
and ensure no dot-dots in internal links.
=> Use permalink in front-matter FOLIO-964

work/amazon-web-services/website-master_cloudformation.yml
=> Add permission to set bucket website config

error.md
=> Add error document

work/amazon-web-services/.gitignore, work/amazon-web-services/website-branch_cloudformation.yml, work/amazon-web-services/website-master_cloudformation.yml
=> Cleanup CloudFormation templates

_data/api.yml
mod-inventory-storage follow rename creator-type to
contributor-name-type
=> FOLIO-903 api-docs config 10

source-code/index.md
Add mod-kb-ebsco mod-codex-ekb ui-eholdings
=> FOLIO-359 list repos 13

work/README.md, work/guide-theme.md, work/maintain-search.md
=> FOLIO-860 search maintenance

source-code/index.md
=> Update list of repositories FOLIO-359

source-code/index.md
Deprecate ui-items and ui-okapi-console.
=> FOLIO-359 list repos 16

_data/api.yml
Add config raml-util mod-user-import
=> FOLIO-903 api docs config 11

_includes/head.html
=> FOLIO-978 upgrade tocbot 1

doc/events.md, doc/index.md
Add new doc for "Events and presentations".
=> FOLIO-873 new doc - events

doc/create-new-repo.md, doc/release-procedures.md, source-code/index.md
Added mod-feesfines to source-code listing.
Enhanced doc: Create a new FOLIO module and do initial setup
=> FOLIO-873 improve docs 19

_data/api.yml
Add location and locationunit for mod-inventory-storage
=> FOLIO-903 api-docs config 12

_data/api.yml
Add mod-feesfines, mod-calendar
=> FOLIO-903 api-docs config 13

source-code/index.md
Add okapi-cli, mod-calendar, ui-calendar, cql2pgjson-java
=> FOLIO-359 list repos 17

doc/code-analysis.md, doc/index.md, guides/index.md, guides/raml-cop.md
Describe installation and usage.
Start to explain the typical messages.
Link to a shell script lint-raml-cop.sh to co-ordinate processing of files.
=> FOLIO-1027 new doc guides/raml-cop

_data/api.yml
Add service-point for mod-inventory-storage
=> FOLIO-903 Update api docs config

source-code/index.md
=> FOLIO-359 list repos 18

source-code/index.md
=> FOLIO-359 list repos 19

guides/automation.md
Mention how to re-run a Jenkins job
=> FOLIO-873 improve docs 25

_data/api.yml
Adjust path for mod-data-loader raml-util DIMPT-3
=> FOLIO-903 api-docs config 15

_data/api.yml
Return old config mod-data-loader raml-util
Until DIMPT-3.
=> FOLIO-903 api-docs config 15b

assets/projectwide-navbar/v0.0.1/projectwide-navbar.html
Perhaps later this “source-code” area can be re-arranged, but it would need some careful thought.
=> FOLIO-1224 fix broken link

source-code/index.md
Rename mod-glint to mod-datasets
=> FOLIO-359 list repos 21

_data/api.yml
=> Update api docs config FOLIO-903

_data/api.yml
Add config for raml-util for mod-kb-ebsco
=> FOLIO-903-api-docs-config-17b

guides/cross-module-joins.md, guides/index.md, start/primer-develop-backend.md
Add new doc /guides/cross-module-joins
=> FOLIO-1251 cross module joins

_data/api.yml, guides/raml-cop.md
Update guides/raml-cop to refer to new folio-tools/lint-raml scripts.
=> FOLIO-1264 lint raml

_config.yml, _data/setup.yml, _data/text-for.yml, _includes/banner-area.html, _includes/head.html, _includes/js-content.html, _includes/projectwide-navbar.html, _sass/_folio.scss, _sass/classic-jekyll-theme.scss, assets/projectwide-navbar/v0.2.0/projectwide-navbar.css, assets/projectwide-navbar/v0.2.0/projectwide-navbar.html
=> FOLIO-1224 Fix top navbar

_data/api.yml
edge-patron
edge-rtac
mod-feesfines
=> FOLIO-903 api docs config 21

source-code/index.md
=> FOLIO-359 list repos 22

tutorials/curriculum/01-clone-build-and-explore-okapi.md, tutorials/curriculum/02-initialize-okapi-from-the-command-line.md, tutorials/curriculum/03-enable-okapi-authentication.md, tutorials/curriculum/05-set-up-the-folio-users-app.md
Need to enable the version of mod-users that matches what was deployed in the previous step.
=> FOLIO-1346 tutorial fix enable mod users

start/index.md, start/overview.md, start/primer-develop-backend.md, start/primer-develop-frontend.md, start/primer-raml.md, start/primer-sys-admin.md, tutorials/curriculum/05-set-up-the-folio-users-app.md, tutorials/curriculum/overview.md
Add initial /start/overview/
 Overview for a new developer.
a high-level summary of “getting started” points for a new developer.
=> FOLIO-873 improve docs 36

_data/api.yml
=> FOLIO-903-api-docs-config-24

_data/api.yml
Rename mod-orders mod-orders-storage
=> FOLIO-903 api-docs config 25

reference/glossary.md, source-code/index.md
mod-erm ui-erm
mod-licenses ui-licenses
mod-orders and rename to mod-orders-storage
ui-receiving
folio-api-tests
=> FOLIO-359 list repos 23

_faqs/explain-permissions-system.md, guidelines/contributing.md, guidelines/create-new-repo.md, guidelines/index.md, guidelines/naming-conventions.md, guides/commence-a-module.md, guides/run-local-folio.md
Added initial doc guidelines/naming-conventions [FOLIO-1390](https://issues.folio.org/browse/FOLIO-1390)
If people have further suggestions then please do.
=> FOLIO-1390 doc naming conventions

community/events.md
Improve the "Events and presentations".
Start linking to a selection of presentations. Added Stripes by Coburn.
Linked to preparation materials.
=> FOLIO-873 improve docs 41

_data/api.yml, source-code/index.md
=> FOLIO-359 list repos 24

_data/api.yml
Soon moving from raml-util
Config is ready for local use.
=> FOLIO-903 Prepare for users-related config change

tutorials/curriculum/05-set-up-the-folio-users-app.md
=> Fix UI module versions

_data/api.yml, reference/api/index.md
Add default config as fallback if missing.
=> FOLIO-903 api docs config 27

_data/api.yml
=> FOLIO-903 api-docs config 28

_data/api.yml
Deploy new configuration for the ramls re-arrangement
=> FOLIO-903 New apidocs config

guidelines/release-procedures.md
Update guidelines/release-procedures.md regarding “release branches”.
See FOLIO-151 and FOLIO-1482
=> FOLIO-1511 release branches

_data/api.yml, source-code/index.md
=> FOLIO-359 list repos 25

guides/index.md, guides/user-experience-design.md, reference/glossary.md
A page that summarises and links to ux.folio.org
Thanks to Stephanie for assistance.
=> FOLIO-873 new doc guides/user-experience-design

_data/api.yml, source-code/index.md
Add mod-aes, mod-kb-ebsco-java, mod-oai-pmh, edge-oai-pmh, ui-audit, stripes
Add api-docs config for mod-kb-ebsco-java
=> FOLIO-359 list repos 26

_data/api.yml
=> FOLIO-903 api-docs config 36

_data/api.yml, source-code/index.md
Add mod-erm-usage ui-erm-usage ui-marcat edge-resolver
=> FOLIO-359 list repos 29

_data/apigroup.yml, reference/api/index.md
Using a configured list of groups of modules.
=> FOLIO-1592 Improve api-docs Table-of-Contents 2

_data/apigroup.yml, _faqs/how-to-configure-api-doc-generation.md, reference/api/index.md
Enable a module to be listed in multiple groups.
=> FOLIO-1592 Improve apidocs Table-of-Contents 3

guides/run-local-folio.md, tutorials/curriculum/05-set-up-the-folio-users-app.md, tutorials/curriculum/06-vm-stable.md, tutorials/curriculum/index.md, tutorials/curriculum/overview.md
Utilise the Q3-2018 VM for the time being.
=> FOLIO-1351 Update curriculum lesson-06

_data/api.yml
mod-inventory-storage
mod-kb-ebsco-java
=> FOLIO-903 Update apidocs config

reference/api/index.md
See notes in [FOLIO-589](https://issues.folio.org/browse/FOLIO-589)
=> FOLIO-589 use new view-2 plain apidocs

_data/api.yml
shared raml-storage for mod-source-record-storage mod-source-record-manager
=> FOLIO-903 Adjust apidocs config

tutorials/curriculum/04-deploy-test-stripes-module.md, tutorials/curriculum/05-set-up-the-folio-users-app.md
Lesson 04 and Lesson 05 have now been overhauled.
We are now back to a working tutorial.
=> FOLIO-1349 update curriculum stripes

_data/api.yml, source-code/index.md
=> FOLIO-359 list repos 32

_data/api.yml
mod-permissions moved from raml-util
=> FOLIO-903 apidocs config 42

source-code/index.md
=> FOLIO-359 Update list of repositories

_data/api.yml
Now RAML 1.0
and removed some *.raml
=>  FOLIO-903 Config apidocs mod-vendors

_data/api.yml, _data/apigroup.yml
Add new for mod-erm-usage-harvester and mod-licenses
=> FOLIO-903 apidocs config 52

_data/api.yml, _data/apigroup.yml
Add mod-invoice and mod-gobi is now raml-1.0
=> FOLIO-903 apidocs config 57

source-code/index.md
Add folio-holdingsiq-client
Add stripes-erm-components ui-plugin-find-license
Remove mod-pg-embed
=> FOLIO-359 list repos 38

_faqs/explain-dates-times.md, guides/dates-and-times.md, guides/index.md
Add new document /guides/dates-and-times
https://issues.folio.org/browse/FOLIO-1778
https://issues.folio.org/browse/UICIRC-178
=> FOLIO-1778 doc dates-and-times

_data/api.yml
For mod-codex-ekb mod-codex-mux mod-notify
=> FOLIO-903 apidocs config 58

guides/devops-introduction.md, guides/devops-verify-task-acceptance.md, guides/index.md
Add new document /guides/devops-verify-task-acceptance
https://issues.folio.org/browse/FOLIO-1775
=> FOLIO-1775 doc verify devops tasks

README.md, _faqs/explain-i18n.md, guides/devops-verify-task-acceptance.md, guides/regular-releases.md
=> FOLIO-873 improve docs 58

_data/api.yml, _data/apigroup.yml
=> FOLIO-903 Config apidocs mod-invoice-storage

_data/api.yml
Large re-arrangement at mod-orders-storage/pull/90
=> FOLIO-903 Config apidocs mod-orders-storage

source-code/index.md
Add mod-invoice mod-invoice-storage edge-sip2
=> FOLIO-359 list repos 39

guides/index.md, guides/performance-optimization.md
New initial document guides/performance-optimization/
Some notes to assist with performance optimization.
Initial content is the call graphs from Okapi logs FOLIO-1856.
=> Add initial guides/performance-optimization FOLIO-1885

tutorials/curriculum/06-vm-stable.md
Use the "Q1-2019" pre-built box.
=> FOLIO-1919 Update tutorial Lesson06 use Q1-2019

source-code/index.md
=> Remove ui-plugin-find-vendor FOLIO-359

guidelines/release-procedures.md, guides/automation.md
See notes and link to branch build at [FOLIO-1963](https://issues.folio.org/browse/FOLIO-1963)
=> FOLIO-1963 Add section "Add to platforms" to guidelines/release-procedures

guidelines/create-new-repo.md, guides/index.md, guides/rename-module.md
Add new document https://dev.folio.org/guides/rename-module/
=> FOLIO-1954 doc rename repository

guides/rename-module.md
=> FOLIO-1954 doc rename repository 2

guides/rename-module.md
Signed-off-by: Peter Murray <jester@dltj.org>
=> Add Lokalise documentation

source-code/index.md
For use with stripes-cli STCLI-133
=> FOLIO-359 List ui-app-template

guides/branch-preview.md, guides/branch_preview.md, guides/index.md
@dcrossleyau - Can you take a quick look and let me know if any changes are required?
=> add branch preview doc to dev docs - FOLIO-2022

_faqs/explain-database-schema.md, guides/branch-preview.md, guides/index.md, reference/glossary.md, source-code/index.md
Add PoC note to branch-preview FOLIO-2022
Fix links to follow move of cql2pgjson RMB-376
=> FOLIO-873 improve docs 68

_data/api.yml, _data/apigroup.yml
=> FOLIO-903 Config apidocs mod-pubsub

_data/api.yml, _data/apigroup.yml
=> FOLIO-903 Config apidocs mod-finance

_data/api.yml, _data/apigroup.yml, source-code/index.md
Config apidocs mod-pub-sub-poc
List mod-pub-sub-poc stripes-final-form
Delist ui-trivial
=> FOLIO-359 FOLIO-903 list new repos

guidelines/contributing.md
Fix section heading levels in guidelines/contributing
and some minor text tweaks.
=> FOLIO-873 improve docs 78

guidelines/contributing.md, guidelines/index.md, guidelines/pull-requests-checklists.md
Add new doc /guidelines/pull-requests-checklists/
Expand /guidelines/contributing/
[FOLIO-2207](https://issues.folio.org/browse/FOLIO-2207)
More related content to come soon.
=> FOLIO-2207 new doc for PR checklists

guidelines/contributing.md, guidelines/development-design-review.md, guidelines/index.md, guidelines/pull-requests-checklists.md, guidelines/which-forum.md, reference/glossary.md
See today's comments at [FOLIO-2214](https://issues.folio.org/browse/FOLIO-2214).
=> FOLIO-2214 new doc guidelines/development-design-review

guides/install-backend-module.md, guides/install-frontend-module.md
=> FOLIO-2177 Improve docs install module

guides/module-descriptor.md
See [FOLIO-2315](https://issues.folio.org/browse/FOLIO-2315)
=> FOLIO-2315 Adjust LaunchDescriptor container Memory setting

community/events.md, guides/module-descriptor.md
Link to new event "FOLIO Roadmap Update (Daisy release) and Demonstration of ERM Apps"
=> FOLIO-873 improve docs 82

guides/run-local-folio.md
Explain testing local deploy back-end module as docker container
=> FOLIO-2356 back-end module local docker container

reference/glossary.md
Hi,
I was asking about acronyms in WOLFCon schedule so after I add an answer, I pushed some "new terms".
Regards,
Claire.
=> Adds glossary terms - SIG's

_data/api.yml, _data/apigroup.yml
Add new configuration for mod-data-export.
=> FOLIO-903 Config apidocs mod-data-export

_faqs/explain-cql.md
Improved the display presentation of the examples.
Enabled direct linking to each.
See the generated in-development [document](http://ssbp-devdoc-prodbranch-chal-240-improve-cql-faq.dev.folio.org.s3-website-us-east-1.amazonaws.com/faqs/explain-cql/).
=> Explain CQL: Improve presentation and linking

guides/automation.md, guides/ftp-ci-server.md
See the generated document [in-development](http://ssbp-devdoc-prodbranch-folio-2450-ftp.dev.folio.org.s3-website-us-east-1.amazonaws.com/guides/ftp-ci-server/).
=> FOLIO-2450 New doc guides/ftp-ci-server

guidelines/release-procedures.md, guidelines/which-forum.md, guides/regular-releases.md
See notes and explanation at [FOLIO-2538](https://issues.folio.org/browse/FOLIO-2538).
=> FOLIO-2538 release-procedures tasks for regular releases

_data/repos.json, source-code/index.md, source-code/map.md, work/maintain-search.md
Link to the new map. Add mod-patron-blocks.
=> FOLIO-359 source code map

_faqs/how-to-which-module-which-interface-endpoint.md, guides/install-backend-module.md, reference/api/index.md, work/maintain-search.md
See https://dev.folio.org/faqs/how-to-which-module-which-interface-endpoint/
=> FOLIO-2589 faq endpoint

community/index.md, guidelines/index.md, guides/index.md, source-code/index.md
Corrected some grammatical typos and errors in this PR.
=> corrected grammatical typos and errors

_data/repos-group.yml, _data/repos.json, reference/glossary.md, source-code/index.md
and follow move of LDP to https://github.com/library-data-platform
=> FOLIO-359 update list of repos

_data/api.yml, _data/apigroup.yml, _data/repos.json
And list new repos: ui-plugin-create-inventory-records, ui-lti-courses, edge-lti-courses
=> FOLIO-903 Config apidocs edge-lti-courses

_data/repos.json, _faqs/how-to-integrate-coverage-reports.md, _faqs/how-to-specify-backend-java-ci.md, guidelines/create-new-repo.md, guides/code-analysis.md
Add FAQs:
https://dev.folio.org/faqs/how-to-specify-backend-java-ci/ (FOLIO-2718 FOLIO-2637)
https://dev.folio.org/faqs/how-to-integrate-coverage-reports/ (FOLIO-2703)
=> FOLIO-873 improve docs 100

guides/automation.md
=> FOLIO-2706 Remove folio-release refenv

README.md, _data/repos-metadata.yml, _faqs/where-is-developer-documentation-located.md, about/thanks.md, guidelines/create-new-repo.md, guides/commence-a-module.md, guides/index.md, guides/visibility-module-docs.md, source-code/map.md
See [FOLIO-2852](https://issues.folio.org/browse/FOLIO-2852)
=> FOLIO-2852 Increase visibility of module documentation

_data/repos.json, guides/visibility-module-docs.md
=> FOLIO-2886 source-code map: Improve extract readme intro

.github/workflows/list-repos-api.sh, .github/workflows/list-repos-api.yml
When there is a change to _data/repos.json file then list the repos that are API-related.
=> FOLIO-722 Add GH workflow actions list-repos-api

_data/releases-backend-q3-2020.json
Later will be automated by workflows
=> FOLIO-2976 Initial gather backend release versions

.github/workflows/get-release-versions.yml, .github/workflows/pr-release-versions.yml, README.md
Creates PR when push to branch ongoing-release-versions by workflow get-release-versions
=> FOLIO-2976 Initial workflow pr-release-versions

_data/releases-backend-q3-2020.json
Manual update. The workflow did not automatically trigger.
=> FOLIO-2976 update backend release versions

_data/repos.json, guides/api-lint.md
See https://dev.folio.org/guides/api-lint/
=> FOLIO-3017 migrate to api-lint

guides/jenkinsfile.md
=> FOLIO-3008 Mention Jenkinsfile doUploadApidocs

guides/automation.md
Based on a conversation on FOLIO's #development channel on Slack on 2021-03-11.
Co-authored-by: Marc Johnson <marc.johnson@k-int.com>
Co-authored-by: Zak Burke <zburke@cornell.edu>
=> Explain npm-folio and npm-folioci

_data/repos.json, guides/automation.md, guides/module-descriptor.md
and explain Docker Hub README generator.
=> OKAPI-1019 Encourage LaunchDescriptor env item documentation

guides/automation.md
- Add juniper release build info
- Remove Honeysuckle release build info
=> Update automation.md to include link to juniper release build.  

_faqs/how-to-get-started-with-rancher.md
docker.dev.folio.org repo does not contain bootstrap-superuser image anymore
folioci repo contains  bootstrap-superuser image
=> Update repo for bootstrap-superuser docker image

_data/api.yml, guides/api-doc.md, guides/api-lint.md
=> FOLIO-903 Config apidocs mod-quick-marc

_data/api.yml
Do not yet have a way to configure
So piggyback on api.yml
=> FOLIO-2922 Add new folio-export-common schemas

guides/automation.md
Add folio-kiwi.  Remove folio-iris.
=> Update reference release envs

_faqs/how-to-archive-repository.md, _faqs/how-to-attend-weekly-meetings.md, _faqs/how-to-get-started-with-rancher.md, _faqs/how-to-raise-devops-ticket.md, _faqs/how-to-request-github-access.md, _faqs/where-is-project-roadmap.md, guidelines/create-new-repo.md, guides/index.md, guides/install-backend-module.md, guides/visibility-module-docs.md, start/primer-sys-admin.md
https://dev.folio.org/faqs/how-to-raise-devops-ticket/
=> FOLIO-3430 Add FAQ how-to-raise-devops-ticket

_data/repos-metadata.yml, guides/visibility-module-docs.md, source-code/map.md
See [FOLIO-3461](https://issues.folio.org/browse/FOLIO-3461)
For example:
https://dev.folio.org/source-code/map/#ui-inventory
https://dev.folio.org/source-code/map/#ui-courses
=> FOLIO-3461 Link source-code/map to relevant userdocs

guides/performance-optimization.md
Giraffe is now maintained at:  https://github.com/library-data-platform/giraffe
=> Update location of Giraffe source code repository

start/index.md
Link to the FOLIO spring base library added to the landing page.
=> Link to the FOLIO spring base library added to the landing page.

.github/workflows/gather-schema-changes/gather_schema_changes.py
also linuxbrew is already on path
=> FOLIO-2976 Worflow: gather-schema-changes: Fix sh.which changed behaviour

.github/workflows/gather-config-apidocs/gather_config_apidocs.py
[FOLIO-1316](https://issues.folio.org/browse/FOLIO-1316)
=> FOLIO-1316 workflow gather-config-apidocs: include gathered endpoints

_sass/_folio.scss, reference/api/endpoints.md
Thanks to https://github.com/tofsjonas/sortable
=> FOLIO-1316 api endpoints: enable table sort

_sass/_folio.scss
Some CSS from tofsjonas/sortable
=> FOLIO-1316 api endpoints: table sort arrows

_data/apigroup.yml, _data/repos.json
Replace with mod-di-converter-storage
=> FOLIO-3683 Rename mod-data-import-converter-storage

_data/config-api-endpoints.json
The GH Workflow failed today. Dunno why, So manual PR.
=> Ongoing config apidocs

.github/workflows/pr-config-apidocs.yml
See repo-sync/pull-request/issues/126
=> FOLIO-2922 Verify fix action pull-request

_sass/classic-jekyll-theme.scss
=> FOLIO-3749 Fix Sass division deprecation warnings

_faqs/how-to-configure-api-doc-generation.md, guidelines/create-new-repo.md, guides/api-doc.md, guides/api-lint.md, guides/commence-a-module.md, guides/describe-schema.md, guides/jenkinsfile.md, guides/raml-cop.md, reference/api/index.md, source-code/map.md
The use via Jenkinsfile is deprecated.
=> FOLIO-3678 Document API-related Workflows

.github/workflows/gather-config-apidocs.yml
Use action git-auto-commit-action v5
=> gather-config-apidocs: upgrade GH Actions

_sass/_folio.scss, reference/api/endpoints.md
https://dev.folio.org/reference/api/endpoints/#sortable
Thanks to https://github.com/tofsjonas/sortable/issues/62
=> Enable basic accessibility for endpoints table

_data/repos-group.yml, _data/repos.json
New repo-type for application descriptor repositories.
=> Add section app to source-code map

_sass/_folio-base.scss, _sass/_folio.scss, _sass/classic-jekyll-theme.scss, stylelint.config.mjs
and fix some, and disable some rules so can see other issues
=> FOLIO-4153 Add stylelint.config.mjs
