folio-org/folio-org.github.io

.gitignore, Gemfile.lock, README.md, _config.yml
Ready to merge.
The README now refers to ‘bundle exec …’ and mentions rbenv.
Exclude files that should not be deployed.
=> Update the build instructions

community/index.md
Provide direct link to Slack, and to the join page,in the top section.
Remove extra links.
=> Link to slack

community/contrib-code.md, community/index.md, doc/index.md, index.md, source-code/index.md
Synchronise copies of doc "CONTRIBUTING.md" and "folio-org.github.io/community/contrib-code.md".
Apply some consistent Markdown style.
=> General tidy and sync copies of contribution guide

_data/api.yml, doc/api/index.md, doc/index.md
DMOD-88
- Improve main page to also link to each raml source
- Better AWS URL
- Add configuration for raml-module-builder
=> DMOD-88 api aws

_data/api.yml, doc/api/index.md
Ready to merge.
Removed configuration for user-related api docs, now moved to raml-util
Removed configuration for mod-users-bl until ready.
=> DMOD-133 move user related 2

_data/api.yml
Remove old top-level file tenantPermissions FOLIO-600
now in folio-org/raml/ramls/mod-permissions
=> FOLIO-600-align-permissions-ramls

_sass/_folio.scss, doc/api/index.md
To highlight anchor sections and table rows,
especially near the bottom of the page.
=> FOLIO-672 Use CSS :target to highlight anchor

doc/index.md, doc/primer-develop-backend.md, doc/primer-develop-frontend.md, source-code/index.md
Add section “Fundamental documentation” and link to the main starting points.
Link to the new “ui-testing” readme doc.
Link to the new “Permissions” doc.
Add basic doc to guide back-end development.
=> Tweak docs 3

doc/reference.md
Ensuring that a permalink in front-matter with trailing slash does work for both our AWS and GitHub site builds.
=> FOLIO-964 test permalink

doc/artifacts.md, doc/reference.md
Ensuring that a permalink in front-matter with trailing slash does work for both our AWS and GitHub site builds.
=> FOLIO-964 test permalink 3

doc/create-new-repo.md
Add note to doc/create-new-repo to use year of creation in the README license statement.
=> FOLIO-360-year-of-creation

_sass/_folio.scss, doc/api/index.md
Use page sections rather than one big table. Each repo has a section with its own table.
Preparing for upcoming in-page table-of-contents.
It is a lot neater, and simpler Liquid code.
=> FOLIO-672 apidocs sections

_includes/head.html, doc/primer-develop-backend.md, search-other.md, search_data.json
If a page's frontmatter has "titleLeader" then use that, otherwise
convert each directory name in the URL to a word.
=> FOLIO-1058 improve page titles

guidelines/release-procedures.md, guides/automation.md
Modify release-related docs to indicate that release artifacts are now initiated via GitHub Release/Tags tab.
See the [build](http://folio-1116-jenkins-release-jobs.dev.folio.org.s3-website-us-east-1.amazonaws.com/guidelines/release-procedures/#build-and-release-artifacts) of this branch.
=> FOLIO-1116 jenkins release jobs

guidelines/release-procedures.md
Updated the "Build and release artifacts" section for Maven-based.
Removed Gradle-based instructions.
=> FOLIO-1116 jenkins release jobs 2

_data/api.yml, reference/api/index.md
Alternative view is not yet available. Currently only mod-kb-ebsco.
=> FOLIO-1253 api-docs exclude view2 raml1

Gemfile, Gemfile.lock
Was v0.3.1 current, now v0.2.4
=> FOLIO-1284 Downgrade jekyll-remote-theme

_data/api.yml
Seems to be experimenting with non-shared configuration for its mod-users-bl pieces.
Has non-standard naming for the git submodule (i.e. ramls/raml rather than ramls/raml-util) so the configuration needs the "excludes" parameter to avoid also processing the RAML files in that area.
=> FOLIO-903 Fix api-docs config mod-users-bl

_data/api.yml
New config for mod-login
Also removed config in “raml” repo for shared-mod-users and shared-mod-login
=> FOLIO-903 api docs config 30

_data/api.yml, _faqs/how-to-configure-api-doc-generation.md
To assist mod-graphql to handle interfaceType=multiple rather than reading ModuleDescriptor
=> MODGQL-110 Add property multiple to apidocs config

reference/api/index.md
The generate-api-docs is now operating again for the default (now "raml1.0") branch.
=> FOLIO-1598 Remove note out-of-date raml-util

source-code/index.md
mod-marcat is now at folio-org
=> FOLIO-359 Update list of repositories 30

reference/api/index.md
Was potential confusion with interface name.
The table rows are not interface names, rather just the raml file from which the docs are generated.
=> Rename apidocs column-1 to Source, use .raml extension

_data/api.yml
mod-permissions are now not shared.
Moving back to its home repo MODPERMS-48 and MODPERMS-49.
So stop processing them in this shared "ramls" repo.
Other configuration was done in pull #308
=> FOLIO-903 Config apidocs mod-permissions

guides/automation.md
Hi David, adding a note that okapi is secured in reference environments. Let me know if I should put this in another place and I'm happy to revise.
=> note that okapi is secured in reference environments

bin/htmlproofer.sh
Use option "--allow-hash-ref" to skip bare "#" hrefs, and so enable real fragment identifiers to be verified.
Had introduced this problem with commit 039c3d2
=> Fix htmlproofer verify fragment identifier

CNAME
Hopefully this will remove the GitHub Pages functionality.  If not, the recommended path forward appears to be "deleting the master branch" ([docs](https://help.github.com/en/articles/unpublishing-a-project-pages-site)).
=> Delete CNAME file to disable GitHub Pages

_data/api.yml, _data/apigroup.yml, source-code/index.md
It was renamed to [deprecated-mod-kb-ebsco-ruby](https://github.com/folio-org/deprecated-mod-kb-ebsco-ruby) and then archived
=> FOLIO-2251 Deprecate mod-kb-ebsco ruby

_data/api.yml, reference/api/index.md
For example:
https://dev.folio.org/reference/api/#mod-notes-types
=> Add html id attribute each row of api docs tables

_faqs/explain-cql.md
Explain which database indexes to use, how to create them,
and left truncation limitations.
Reword "exact match operator"; this is misleading and is replaced by
"word match operator".
Remove wrong sentence about case/accents sensitivity.
Directly link to RMB documentation.
=> Explain db indexes, reword exact to field, remove case/accents sentence.

guidelines/release-procedures.md
Developers should clean their development directories after
release. Using mvn release:clean will not only clean the main
directory but also all maven sub-modules directories.
=> Run mvn release:clean after release

guides/install-backend-module.md
Commence a list of typical mistakes with the readiness of back-end modules, before attempting to aadd them to reference environments.
=> FOLIO-873 improve docs

_data/api.yml
**Attention**:
Would mod-finance please migrate to use:
https://dev.folio.org/reference/api/#explain-api-doc
https://dev.folio.org/reference/api/#explain-api-lint
The tools that you are using were deprecated long ago.
=> FOLIO-903 Config apidocs mod-finance

_data/api-missing.yml, reference/api/index.md
Add a list of new (mostly OAS) modules that are missing the configuration for generating and publishing their API documentation.
https://dev.folio.org/reference/api/#missing-api-documentation
=> FOLIO-3231 List repos that are missing api-doc

_data/api.yml
**Attention**:
Would mod-inventory-storage please migrate to use:
https://dev.folio.org/reference/api/#explain-api-doc
https://dev.folio.org/reference/api/#explain-api-lint
The tools that you are using were deprecated long ago.
=> FOLIO-903 Config apidocs mod-inventory-storage

guidelines/github-actions-frontend.md
Two minor but crucial adjustments:
* It is necessary to add a remote before fetching its branches
* `origin` and `head` were transposed
@dcrossleyau , @ankitasen-ubmainz, tagging you here in the comments since I don't have write privileges in this repository. Please merge this if it looks correct to you. Thanks!
Refs [FOLIO-3290](https://issues.folio.org/browse/FOLIO-3290)
=> FOLIO-3290 correct instructions for building forked repos

_data/api.yml
**Attention**:
Would mod-erm-usage-harvester please migrate to use:
https://dev.folio.org/reference/api/#explain-api-doc
https://dev.folio.org/reference/api/#explain-api-lint
The CI tools that you are using were deprecated long ago.
=> FOLIO-903 Config apidocs mod-erm-usage-harvester

.github/workflows/list-repos-api.yml
Running list-repos-api.sh on the docker container provided by
https://github.com/awesome-global-contributions/action-yq
takes 23 seconds, while running it directly on GitHub Action's
ubuntu-latest only takes 1 second.
ubuntu-latest comes with all required dependencies pre-installed:
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
=> list-repos-api without docker container

.github/workflows/gather-schema-changes.yml, .github/workflows/gather-schema-changes/gather_schema_changes.py, .github/workflows/gather-schema-changes/requirements.txt
Call `secure_filename` before passing a filename to `open`, `os.walk` or `shutil.copytree`.
Components of the filename come from an external JSON fetched from a URL. This may result in a path traversal vulnerability: https://cwe.mitre.org/data/definitions/23.html Security scanners like snyk.io report that this code might be vulnerable.
The risk may be low, however, fixing the code is less effort than the reviews that the FOLIO security team needs to do on gather_schema_changes.py every 30 days. Safety first!
=> Prevent path traversal vulnerability (CWE-23)

guides/branch-preview-kubernetes.md, guides/jenkinsfile.md
https://issues.folio.org/browse/FOLIO-3407
It reduces the container size, attack surface, comlexity and maintenance effort.
=> FOLIO-3409: Prefer wget over curl for healthChkCmd

guides/folio-vertx-lib.md, guides/index.md
Adds new section https://dev.folio.org/guides/#module-development-bases to introduce libraries and frameworks and approaches that form the basis for module development.
=> Add guides section: Module development bases

Gemfile
Nokogiri v1.13.9 upgrades the packaged version of its dependency libxml2 to v2.10.3 from v2.9.14.
libxml2 v2.10.3 addresses the following known vulnerabilities:
* CVE-2022-2309 = https://nvd.nist.gov/vuln/detail/CVE-2022-2309
* CVE-2022-40303 = https://nvd.nist.gov/vuln/detail/CVE-2022-40303
* CVE-2022-40304 = https://nvd.nist.gov/vuln/detail/CVE-2022-40304
For details see https://github.com/advisories/GHSA-2qc6-mcvw-92cw
=> nokogiri 1.13.9 fixing libxml2 vulnerabilities

Gemfile, Gemfile.lock
Quote from https://jekyllrb.com/docs/ :
"If you are using Ruby version 3.0.0 or higher, [...] fix it by adding webrick to your dependencies"
=> Add webrick for Ruby 3

_data/config-apidocs.json
No, a test also failed. It is a problem with the dependency action `repo-sync/pull-request` (which had a new release today) for our pr-config-apidocs.yml and pr-release-versions.yml workflows.
Will disable our Workflows gather-config-apidocs.yml and get-release-versions.yml which will trigger those PR Workflows if there are changes.
=> Ongoing config apidocs

.github/workflows/gather-config-apidocs/gather_config_apidocs.py, _data/repos-group.yml, _data/repos.json
A new type of backend module repository was added (`mgr-*`) contravening the module naming convention `mod-*`
Not sure what it means.
Fix the source-code/map/ and the gather-config-apidocs Workflow.
=> Fix source-code map and gather-config-apidocs

.github/workflows/gather-config-apidocs.yml, .github/workflows/gather-schema-changes.yml, .github/workflows/get-release-versions.yml
Keep up-to-date with dependent GitHub Actions. [FOLIO-3944](https://issues.folio.org/browse/FOLIO-3944)
=> FOLIO-3944 Upgrade Actions for API-related Workflows

guidelines/naming-conventions.md
During a recent review of the TC's module evaluation process, it was recommended that the policy link to the naming guidelines
As part of reviewing those recommendations, I raised [concerns](https://github.com/folio-org/tech-council/pull/55/files#r1472625295) about outdated advice around JSON API
This pull request removes that advice
=> Remove outdated advice about JSON API

source-code/map.md
Because stripes repoName did not contain a dash, the ToC sorting into alpha groups was broken for all stripes repos.
https://dev.folio.org/source-code/map/#stripes
=> Fix source-code map alphabeticiser

.github/workflows/jekyll.yml
variable $default-branch can only be used in Workflow templates
=> FOLIO-4085 Fix Jekyll Workflow on push branches 

_data/api-missing.yml
Their api-lint Workflow reports brokenness, but is not being resolved. Hence when api-doc attempts to build docs on merge to mainline, it cannot.
=> FOLIO-3678 Denote missing api-doc mod-mosaic

Gemfile.lock
https://folio-org.atlassian.net/browse/SECURITY-387
https://github.com/advisories/GHSA-c2f4-jgmc-q2r5
The REXML gems from 3.3.3 to 3.4.1 have a DoS vulnerability when parsing XML containing multiple XML declarations. If you need to parse untrusted XMLs, you may be impacted to these vulnerabilities.
=> SECURITY-387: Upgrade rexml from 3.4.1 to 3.4.4 fixing CVE-2025-58767
